### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by xjrk58** [Kirill5k/kafka-connect-http#1]
I would like to contribute into this connector, but unfortunately it doesn't have any license file. Could you maybe add one?

**Comment by Kirill5k** [comment]
Wasnt expecting anyone would be willing to contribute to it, so I never really bothered with licences.

I'll update it today.

**Comment by xjrk58** [comment]
Thanks a lot

**Comment by Kirill5k** [comment]
Licence has been added
